Mim 1975 new table into ds
statisticsnorway/design-system pull request #606
Opened 2024-08-27 12:35 UTC by Carl-OW

2024-08-27 13:22 UTC, ssb-cgn commented on src/pages/Components/ComponentsInfo/TableInfo.jsx
> +import "../../../style/_table.scss";
Skal ikke trenge å legge til styling i designsystemet

2024-08-27 13:23 UTC, ssb-cgn commented on src/style/_table.scss
> +
Denne filen er unødvendig, styling kommer fra komponentbibiloteket

2024-08-27 13:24 UTC, ssb-cgn requested changes
Fjerne filen for styling til table og kjøre gjennom linting. Ser også at tabellen blir litt rar i visningen

2024-08-27 13:33 UTC, ssb-cgn commented on src/pages/Components/ComponentsInfo/TableInfo.jsx
> +const codeReact = `
Viser eksempler for Faktaboks istedenfor Tabell

2024-09-03 08:58 UTC, ssb-cgn submitted a review, later dismissed

2024-09-03 11:35 UTC, ssb-cgn approved these changes

2024-09-03 11:59 UTC, johnnadeluy approved these changes
👏

2024-09-03 11:59 UTC, merged